Repository Mojix-Proyecto-Ing-Soft/sariri-frontend, pull requests merged in 2022-09, with the labels that each got.

#4 Bug/home
  src/App.jsx
  src/assets/mapaxd.png
  src/components/Info-Hotel/Calendar.js
  src/components/Info-Hotel/Card.jsx
  src/components/Info-Hotel/CommentUser.jsx
  src/components/Info-Hotel/CommetsOthersUsers.jsx
  src/components/Info-Hotel/Contacts.jsx
  src/components/Info-Hotel/FavButton.jsx
  src/components/Info-Hotel/Huespedes.jsx
  src/components/Info-Hotel/Mapa.jsx
  src/components/Info-Hotel/Reservar.jsx
  src/components/Info-Hotel/Services.jsx
  src/components/Info-Hotel/Stars.jsx
  src/components/Info-Hotel/imagesList.jsx
  src/components/container/ScrollReveal.css
  src/components/container/ScrollReveal.jsx
  src/pages/Home.jsx
  src/pages/InfoHoteles.js
Labels: bug

#6 Feature/info hotel
  package-lock.json
  src/App.jsx
  src/api/index.js
  src/components/Info-Hotel/Calendar.js
  src/components/Info-Hotel/CommentUser.jsx
  src/components/Info-Hotel/Contacts.jsx
  src/components/Info-Hotel/Huespedes.jsx
  src/components/Info-Hotel/Mapa.jsx
  src/components/Info-Hotel/Reservar.jsx
  src/components/Info-Hotel/Services.jsx
  src/components/Info-Hotel/Stars.jsx
  src/components/Info-Hotel/imagesList.jsx
  src/components/PlaceDetails/PlaceDetails.js
  src/components/Principal/Calendar.js
  src/pages/Book.jsx
  src/pages/InfoHoteles.js
Labels: feature

#7 Fix/sign in up merge
  .gitignore
  .idea/.gitignore
  .idea/modules.xml
  .idea/sariri_devs.iml
  .idea/vcs.xml
  package-lock.json
  package.json
  src/components/Navbar.jsx
  src/context/googleContext.js
  src/pages/Home.jsx
  src/pages/SignIn-Up.js
Labels: feature

#8 Fix/alerts
  src/components/List/List.js
  src/components/Navbar.jsx
  src/components/PlaceDetails/PlaceDetails.js
  src/pages/InfoHoteles.js
  src/pages/Profile.js
  src/pages/SignIn-Up.js
Labels: fix

#9 popUp message for filter added and Favorites Hotels page created
  src/App.jsx
  src/components/List/List.js
  src/components/Map/Map.js
  src/components/Navbar.jsx
  src/pages/Favorites.jsx
  src/pages/Home.jsx
Labels: fix

#10 Feature/hotel-fav
  public/index.html
  src/App.jsx
  src/api/index.js
  src/components/FavoritesCard/FavoritesCard.jsx
  src/components/Footer.jsx
  src/components/Hotels.jsx
  src/components/Info-Hotel/FavButton.jsx
  src/components/Info-Hotel/Huespedes.jsx
  src/components/Info-Hotel/InfoHoteles.js
  src/components/Info-Hotel/Reservar.jsx
  src/components/Info-Hotel/Services.jsx
  src/components/Info-Hotel/Stars.jsx
  src/components/Info-Hotel/subcomponents/Calendar.js
  src/components/Info-Hotel/subcomponents/Card.jsx
  src/components/Info-Hotel/subcomponents/CommentUser.jsx
  src/components/Info-Hotel/subcomponents/CommetsOthersUsers.jsx
  src/components/Info-Hotel/subcomponents/Contacts.jsx
  src/components/Info-Hotel/subcomponents/FavButton.jsx
  src/components/Info-Hotel/subcomponents/Huespedes.jsx
  src/components/Info-Hotel/subcomponents/Mapa.jsx
  src/components/Info-Hotel/subcomponents/Reservar.jsx
  src/components/Info-Hotel/subcomponents/Services.jsx
  src/components/Info-Hotel/subcomponents/Stars.jsx
  src/components/Info-Hotel/subcomponents/imagesList.jsx
  src/components/List/List.js
  src/components/Map/Map.js
  src/components/Navbar.jsx
  src/components/PlaceDetails/PlaceDetails.js
  src/components/Principal.jsx
  src/components/Principal/Calendar.js
  src/components/Principal/Select.js
  src/context/googleContext.js
  src/index.css
  src/index.js
  src/pages/Favorites.jsx
  src/pages/Home.jsx
  src/pages/HotelInfo_Fav.jsx
  src/pages/Profile.js
  src/pages/SignIn-Up.js
  src/utils/utils.js
Labels: feature
